### ISSUE TITLE
Object of type 'map' has no len()

### ISSUE THREAD

**Issue by mariamaseng** [kdm9/SRApy#5]
get-project-sras.py -e XX -p 489090 

typeError: object of type 'map' has no len()

**Comment by kdm9** [comment]
can you please post at least the traceback, if any?

**Comment by kdm9** [comment]
I've found all occurrences of map and done list(map(...)) so it should be fixed in master.

**Comment by kdm9** [comment]
the fix should be in version 0.1.19 on pypi, do `pip install -U srapy` to upgrade. Reopen the bug if the issue persists
